### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by jonathan-dejong** [gladchinda/web-speech-demo#1]
Hi mate!

Just wanted to thank you. This repo gave me a head start on quickly throwing together a web app for my grandpa who needed some super simple text-to-speech due to inability to speak properly (old age, leukemia and stroke). 

I managed to whip this together in a couple of hours thanks to you: 
https://prata.jonte.dev/
(it's hard-coded to swedish).

So thank you! Looking forward to seeing him start using it tomorrow :)

**Comment by gladchinda** [comment]
Hi Jonathan,

I'm glad to hear that this repo was very instrumental in helping you put the text-to-speech app together. I do hope that the app ease communications between you both.

Thanks for sharing.
